# Permanent redirect to HTTPS
0.0.0.0:80, ucuntu.com, www.ucuntu.com {
  log stdout
  errors stderr
  redir https://ucuntu.com{uri} 301
}

https://ucuntu.com {
  log stdout
  errors stderr
  root /srv
}
